### ISSUE TITLE
Further reading

### ISSUE THREAD

**Issue by leo92ra** [tamap94/ds-capstone-alzheimers-#101]
- [x] check how to improve accuracy of the models
- [x] check baseline paper, accuracy of other tests
- [x] look for more ideas of what to try 
- [x] research most important brain areas for AD diagnosis

**Comment by tamap94** [comment]
- Image segmentation is quite often used to define AD relevant brain structures 
- Hippocampus mask can be used to extract the Hippocampus from the 3D image

**Comment by tamap94** [comment]
Accuracy on the different brain areas: 
Total hippocampus: 71.6% 
Medial temporal lobe: 64.7 % 
Lateral ventricles: 61.9%

**Comment by tamap94** [comment]
Visual assessment discriminates mild AD from normal aging with around 84% accuracy (80-85% sensitivity and specificity, prevalence in people older 65 is around 11%) (https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3312396/)
