### ISSUE TITLE
Finalize EDA

### ISSUE THREAD

**Issue by tamap94** [tamap94/ds-capstone-alzheimers-#12]
- [x] add comments and text 
- ~~[ ] write functions for code that is repeated~~ 
- ~~[ ] move code/functions into Python scripts~~

**Comment by leo92ra** [comment]
- [ ] use same labelling (e.g. dementia/Alzheimer)
- [ ] similar colour codes

**Comment by ValleSoYeah** [comment]
- [ ] combine OASIS and ADNI in one notebook
- [ ] highlight differences in the two datasets (also in images) and the need to consolidate the two
- [ ]

**Comment by tamap94** [comment]
OASIS numerical and image data final EDA completed @tamap94
