### ISSUE TITLE
Background research 

### ISSUE THREAD

**Issue by tamap94** [tamap94/ds-capstone-alzheimers-#14]

**Comment by ValleSoYeah** [comment]
- [ ] What do doctors look at in the image? @leo92ra 
- [ ] What are the processing steps of the raw images @ValleSoYeah 
- [ ] What do all the (non-image) files mean?  @deneick 
- [ ] What does Freesurfer do? @ValleSoYeah 
- [ ] What does T1 scan mean? @anyone
- [ ] General Alzheimer research? @tamap94 
- [ ] (What kind of models were used to predict Alzheimers?)
- [ ] How does MRI work? @tamap94
