### ISSUE TITLE
Discuss team work structure 

### ISSUE THREAD

**Issue by tamap94** [tamap94/ds-capstone-alzheimers-#21]
- [x] When to meet? 
- [x] Set individual goals
- [x] Who wants to do what?
- [x] Where to combine results and stuff?
- [x] GitHub Branch management
- [x] Decide on presentation tool

**Comment by ValleSoYeah** [comment]
- Daily Team-meetups at 9:30
- Weekly Repo-cleanup (Fridays)
- work in GoogleDoc file for information exchange
- update Organisation-Markdown file regularly with info from GDoc
- create separate MD files for Research,... etc...
- delete branches after merging
- name new branches as "name-purpose"
