### ISSUE TITLE
Select suitable metric 

### ISSUE THREAD

**Issue by tamap94** [tamap94/ds-capstone-alzheimers-#5]
- Hospital: false positives are not that dramatic, since doctors anyway should do a second test in this case, keep false negatives low -> F2 score (more weight on recall than on precision) 
- general: accuracy should be pretty good to make sure that the predictions are correctly 
- most important: accuracy, second: reduce false negatives without losing accuracy

**Comment by ValleSoYeah** [comment]
what metric can we use for an unbalanced dataset?

**Comment by tamap94** [comment]
- have an imbalanced dataset 
- F2 score
