### ISSUE TITLE
Look into ADNI

### ISSUE THREAD

**Issue by ValleSoYeah** [tamap94/ds-capstone-alzheimers-#62]
- [x] what data is available?
- [x] can we match numerical and image data by subjectID?
- [x] how can we combine OASIS and ADNI? [check paper](https://www.sciencedirect.com/science/article/pii/S2213158222000584#f0010)
- [x] what files are provided? 
- [x] how long would the download take?
- [x] combine with PET images?

DoD: 
Decided whether to use or not to use the ADNI dataset
Decision due morning of Aug 23rd

**Comment by tamap94** [comment]
- Non-image data @leo92ra 
- Image-related data @tamap94
