### ISSUE TITLE
Explore cloud solutions for a 3D-CNN

### ISSUE THREAD

**Issue by tamap94** [tamap94/ds-capstone-alzheimers-#67]
- [x] select suitable Cloud environment 
   - start with Google Cloud -> does not allow to use GPUs in the free version 
   - check out Azure 
- [x] create GCP account 
- [ ] ~~create Azure account~~
- [ ] set up notebooks 
- [x] upload images to cloud
- [x] how to collaborate in the cloud? 
- [x] Apply for free TPUs in Google Cloud

**Comment by ValleSoYeah** [comment]
- waiting for response to activate TPU in Cloud Project
- TPU in Colab works only sometimes in free version
- OASIS images are uploaded to Google Clopud bucket
