### ISSUE TITLE
Imagine stakeholder 

### ISSUE THREAD

**Issue by tamap94** [tamap94/ds-capstone-alzheimers-#7]
- Hospital: save time for the doctor, be more accurate than the doctor, reduce human errors, avoid using more expensive diagnostic tools 
- Alzheimer's Association: find as many mild demented Alzheimer cases very early, can treat it early and help the patients 
- Research: find patterns in images, detect novel structural changes that are associated with dementia

**Comment by ValleSoYeah** [comment]
what has to be done based on our stakeholder?

**Comment by tamap94** [comment]
Stakeholder: Neurologist. The final product would be a model/an application where the stakeholder can upload the MRI images which get then processed and fed into the model with the output 'demented' and 'non-demented' together with the probability for each class.
