### ISSUE TITLE
investigate difference to kaggle

### ISSUE THREAD

**Issue by ValleSoYeah** [tamap94/ds-capstone-alzheimers-#77]
- [ ] how are the kaggle images different? contrast?
- [x] where do the kaggle images come from? -> contacted one of the contributors on LinkedIn to get more information @tamap94 
- [x] does our model with less kaggle images perform equally bad?

**Comment by deneick** [comment]
Kaggle dataset result after 10 epochs:

250: 0.7
500: 0.78
1000: 0.85
2000: 0.92
4000: 0.98

**Comment by tamap94** [comment]
Dataset with a bit more information where it comes from: 

https://www.kaggle.com/datasets/sachinkumar413/alzheimer-mri-dataset
